### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by XahidEx** [OmkarK45/omkarkulkarni.dev#1]
Fixed

**Comment by OmkarK45** [comment]
Hi there! Make sure you put them on Vercel App Dashboard. 

```
https://vercel.com/<your vercel userrname>/<your vercel app name>/settings/environment-variables
```
![image](https://user-images.githubusercontent.com/45557594/150689096-00aac28e-bcbc-48e5-a4ee-3da8248a5678.png)

You can obtain API key from twitter developers portal

**Comment by XahidEx** [comment]
I did that too. But same error. &
Another question is Do I must have to put all the environments? Or using two (Database, Twitter) enough?

**Comment by XahidEx** [comment]
Bro, Help me. I've added all the environments. Still the same issue. What do I have to do? Or do I have to make any changes in other sections? Please kindly tell me that. I'm trying too hard to fix everything for 3-4 days. Old repo works fine. But when I try the leerob.io update repo, It shows that issue. What do I need to change bro?

**Comment by OmkarK45** [comment]
> Bro, Help me. I've added all the environments. Still the same issue. What do I have to do? Or do I have to make any changes in other sections? Please kindly tell me that. I'm trying too hard to fix everything for 3-4 days. Old repo works fine. But when I try the leerob.io update repo, It shows that issue. What do I need to change bro?

Okay. Send a link to your repo here. I'll take a look

**Comment by XahidEx** [comment]
https://github.com/XahidEx/Xahid.Live

I've tried with setting up all the environments (Cloned from your repo) 💟

**Comment by XahidEx** [comment]
![Screenshot_20220124-125714_Brave](https://user-images.githubusercontent.com/88249321/150736069-3cb13119-45d3-43f2-ae6e-b81ee1184858.jpg)
If It's a
![Screenshot_20220124-125718_Brave](https://user-images.githubusercontent.com/88249321/150736078-016b730e-7ed1-49b3-bc4d-0e842bc89048.jpg)
 Problem with my github or vercel? Same happening when I use the leerob.io repo. It was alright before. I've even tried with different github and vercel, just for testing. Neither worked

**Comment by OmkarK45** [comment]
maybe try console logging if you get tweets from getTweets function. There would be likely a helpful response there. 
https://github.com/XahidEx/Xahid.Live/blob/1daee4d0716713c8041f7d7d740221247eb9c05e/lib/twitter.ts#L27
Add a console log(response) here to check if you receive tweets from twitter

**Comment by OmkarK45** [comment]
2/n make sure you are using correct Twitter API key. it looks like 
```
AAAAAAAAAAAAAAAAAAAAALFhVgEAAAAAZBjuVTHqLNAjGZqBrFXXXXX%2FOc%3DtGgIS1XLy34lsdfnvs6osVrTxLnsD6IwlWQFU3xtA8AWEPMIO2
```

in the above format

**Comment by XahidEx** [comment]
Thanks brother.. Another question, Do I need to use api OAuth 1.0 or 0Auth 2.0?

**Comment by XahidEx** [comment]
![Screenshot_20220124-135612_Brave](https://user-images.githubusercontent.com/88249321/150743235-6a527668-39ef-4b64-9551-6eac09f2c659.jpg)
First one right?

**Comment by XahidEx** [comment]
I did try with the API key. Should I use API secret?

**Comment by OmkarK45** [comment]
> I did try with the API key. Should I use API secret?

Use bearer token and save it in env of vercel as TWITTER_API_KEY

![image](https://user-images.githubusercontent.com/45557594/150744829-cd1e578f-1cb9-4eba-b427-7d73c91e2a00.png)

**Comment by XahidEx** [comment]
Yaaahoooo thanks a lot brother 🙈🙈💟💟💟💟💟💟💟💟 fixed 🧡😅

**Comment by OmkarK45** [comment]
> Yaaahoooo thanks a lot brother 🙈🙈💟💟💟💟💟💟💟💟 fixed 🧡😅

Awesome! Nice Work!!
