### ISSUE TITLE
Done

### ISSUE THREAD

**Issue by XahidEx** [OmkarK45/omkarkulkarni.dev#2]
Fixed

**Comment by OmkarK45** [comment]
https://github.com/OmkarK45/omkarkulkarni.dev/blob/2d9dd27f93a5585f00918d9129d7e225adf9808b/styles/global.css#L5

**Comment by XahidEx** [comment]
Bro, I've tried a lot changing so many things. But the background color black doesn't change. I was successful to change everything else except body background color. I wanted to make my dark mode a little bit blue. Not fully black. Would you please tell me a solution. Please
