### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by XahidEx** [OmkarK45/omkarkulkarni.dev#5]
Whenever I tried to use any kind of analytics, It wasn't working. What's the issue?

**Comment by OmkarK45** [comment]
Hey there, thanks for reaching out. I would need more information. What analytics do you want to add? You will need to refer analytics' documentation for integration instructions.

**Comment by XahidEx** [comment]
I've tried using various analytics. But the problem is It doesn't work. I mean It doesn't track anything. Have you tried it yourself? Google Analytics, Umami or Plausible
